"""Adicionando campo setor ao modelo Notebook

Revision ID: 827e0f0d5828
Revises: aa9973100d47
Create Date: 2024-12-22 15:45:30.034319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827e0f0d5828'
down_revision = 'aa9973100d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setor', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notebook', schema=None) as batch_op:
        batch_op.drop_column('setor')

    # ### end Alembic commands ###
