"""Initial migration

Revision ID: aa9973100d47
Revises: 
Create Date: 2024-12-22 15:35:32.756736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9973100d47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('colaborador', sa.String(length=100), nullable=True),
    sa.Column('motivo_entrada', sa.String(length=255), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notebook')
    # ### end Alembic commands ###
